import { V2Merchant, V2ExpiredOffer, V2DuplicateRecord } from "./types";

export const v2Merchants: V2Merchant[] = [
  {
    id: "MID-10042",
    name: "Sam's Club",
    source: "Augeo",
    subcategory: "Warehouse Retail",
    emoji: "\uD83D\uDED2",
    emojiBg: "bg-yellow-100",
    category: "Retail",
    activeOffers: 3,
    expiredOffers: 0,
    publishers: ["Verizon", "JD Perks"],
    status: "active",
    revShare: "8.5%",
  },
  {
    id: "MID-10089",
    name: "Disney+",
    source: "EBG",
    subcategory: "Streaming",
    emoji: "\uD83C\uDFAC",
    emojiBg: "bg-violet-100",
    category: "Entertainment",
    activeOffers: 2,
    expiredOffers: 1,
    publishers: ["Verizon"],
    status: "attention",
    revShare: "12.0%",
  },
  {
    id: "MID-10156",
    name: "Active&Fit Direct",
    source: "Augeo",
    subcategory: "Fitness",
    emoji: "\uD83D\uDCAA",
    emojiBg: "bg-green-100",
    category: "Health & Wellness",
    activeOffers: 1,
    expiredOffers: 0,
    publishers: ["Optum"],
    status: "active",
    revShare: "10.0%",
  },
  {
    id: "MID-10207",
    name: "Papa John's",
    source: "Direct",
    subcategory: "Food & Dining",
    emoji: "\uD83C\uDF55",
    emojiBg: "bg-red-100",
    category: "Food & Dining",
    activeOffers: 2,
    expiredOffers: 0,
    publishers: ["Verizon"],
    status: "review",
    revShare: "7.0%",
    isDuplicate: true,
  },
  {
    id: "MID-10331",
    name: "Amazon",
    source: "Augeo",
    subcategory: "Retail / E-commerce",
    emoji: "\uD83D\uDCE6",
    emojiBg: "bg-amber-100",
    category: "Retail",
    activeOffers: 4,
    expiredOffers: 0,
    publishers: ["Verizon", "JD Perks", "Optum"],
    status: "active",
    revShare: "9.0%",
  },
];

export const v2ExpiredOffers: V2ExpiredOffer[] = [
  {
    id: "OID-88231",
    name: "Disney+ 3-Month Trial",
    merchantName: "Disney+",
    publisher: "Verizon",
    expiredDate: "Mar 1, 2026",
  },
  {
    id: "OID-77843",
    name: "Sam's Club Winter Deal",
    merchantName: "Sam's Club",
    publisher: "JD Perks",
    expiredDate: "Feb 28, 2026",
  },
  {
    id: "OID-91002",
    name: "Amazon Holiday Bundle",
    merchantName: "Amazon",
    publisher: "Verizon",
    expiredDate: "Jan 15, 2026",
  },
];

export const v2Duplicates: V2DuplicateRecord[] = [
  {
    nameA: "Papa John's",
    idA: "MID-10207",
    offersA: "2 offers \u00B7 1 campaign",
    nameB: "Papa Johns Pizza",
    idB: "MID-10208",
    offersB: "1 offer \u00B7 0 campaigns",
    matchPercent: 95,
  },
];
