import { V2Campaign } from "./types";

export const v2Campaigns: V2Campaign[] = [
  {
    id: "CID-3406",
    name: "Spring Savings 2026",
    publisherSubtitle: "Verizon",
    publisher: "Verizon",
    campaignType: "Campaign",
    channels: ["Email", "Push", "In-App"],
    timeline: "Mar 2026",
    approvalStatus: "approved",
    deliveryStatus: "live",
    impressions: "1.1M",
    ctr: "0.39%",
    redemptions: "1,203",
  },
  {
    id: "CID-3407",
    name: "Yardi March Spotlight",
    publisherSubtitle: "Yardi",
    publisher: "Yardi",
    campaignType: "Spotlight",
    channels: ["Email", "Push", "In-App"],
    timeline: "Mar 2026",
    approvalStatus: "approved",
    deliveryStatus: "live",
    impressions: "310K",
    ctr: "0.35%",
    redemptions: "869",
  },
  {
    id: "CID-3408",
    name: "ConExpo (March 2026)",
    publisherSubtitle: "John Deere",
    publisher: "John Deere",
    campaignType: "Event",
    channels: ["Email", "SMS"],
    timeline: "Mar 2026",
    approvalStatus: "pending",
    deliveryStatus: "scheduled",
    impressions: "420K",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3409",
    name: "OTC Pilot Plus Up (March 2026)",
    publisherSubtitle: "John Deere",
    publisher: "John Deere",
    campaignType: "Program",
    channels: ["Email"],
    timeline: "Mar 2026",
    approvalStatus: "pending",
    deliveryStatus: "scheduled",
    impressions: "420K",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3410",
    name: "JDF Awareness (April 2026)",
    publisherSubtitle: "John Deere",
    publisher: "John Deere",
    campaignType: "Campaign",
    channels: ["Email", "SMS", "Push"],
    timeline: "Apr 2026",
    approvalStatus: "planning",
    deliveryStatus: "planned",
    impressions: "420K",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3411",
    name: "PowerPlan (May 2026)",
    publisherSubtitle: "John Deere",
    publisher: "John Deere",
    campaignType: "Campaign",
    channels: ["Email"],
    timeline: "May 2026",
    approvalStatus: "planning",
    deliveryStatus: "planned",
    impressions: "420K",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3412",
    name: "Full Dealer Expansion (July 2026)",
    publisherSubtitle: "John Deere",
    publisher: "John Deere",
    campaignType: "Expansion",
    channels: ["Email", "SMS"],
    timeline: "Jul 2026",
    approvalStatus: "planning",
    deliveryStatus: "planned",
    impressions: "420K",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3413",
    name: "Birthday Bundle",
    publisherSubtitle: "Verizon",
    publisher: "Verizon",
    campaignType: "Collection",
    channels: ["Email"],
    timeline: "Ongoing",
    approvalStatus: "planning",
    deliveryStatus: "planned",
    impressions: "1.2M",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3414",
    name: "NASCAR (Straight Talk)",
    publisherSubtitle: "Verizon",
    publisher: "Verizon",
    campaignType: "Sports",
    channels: ["Email", "Push"],
    timeline: "TBD",
    approvalStatus: "planning",
    deliveryStatus: "planned",
    impressions: "1.2M",
    ctr: "—",
    redemptions: "—",
  },
  {
    id: "CID-3415",
    name: "FIFA (Total Wireless)",
    publisherSubtitle: "Verizon",
    publisher: "Verizon",
    campaignType: "Gaming",
    channels: ["Email", "Push"],
    timeline: "TBD",
    approvalStatus: "planning",
    deliveryStatus: "planned",
    impressions: "1.2M",
    ctr: "—",
    redemptions: "—",
  },
];
