/**
 * @file Sample data for Member CRM feature
 * @description Mock data for development and demos
 */

import {
  Member,
  MemberWithPoints,
  PointsTransaction,
  Receipt,
  Promotion,
  Program,
} from "./types";

export const samplePrograms: Program[] = [
  {
    id: "prog-optum-001",
    name: "Optum HealthyBenefits+",
    displayName: "Optum Rewards Points",
    partnerName: "Optum",
    isActive: true,
  },
  {
    id: "prog-wellness-001",
    name: "Wellness Plus",
    displayName: "Wellness Points",
    partnerName: "WellnessPlus",
    isActive: true,
  },
];

export const samplePromotions: Promotion[] = [
  {
    id: "promo-001",
    name: "Buy 3 Colgate, Get $5",
    description:
      "Purchase 3 Colgate toothpaste products and earn $5 in rewards",
    programId: "prog-optum-001",
    rewardType: "points",
    rewardAmount: 500,
    isActive: true,
  },
  {
    id: "promo-002",
    name: "Wellness Products 10% Back",
    description: "Earn 10% back on qualifying wellness products",
    programId: "prog-optum-001",
    rewardType: "points",
    rewardAmount: 0, // Calculated based on receipt
    isActive: true,
  },
  {
    id: "promo-003",
    name: "Healthy Snacks Bonus",
    description: "Extra 100 points when you buy healthy snacks",
    programId: "prog-optum-001",
    rewardType: "points",
    rewardAmount: 100,
    isActive: true,
  },
];

export const sampleTransactions: PointsTransaction[] = [
  {
    id: "txn-001",
    accountId: "acc-789xyz",
    programId: "prog-optum-001",
    transactionType: "earn",
    sourceType: "receipt",
    pointsAmount: 50,
    usdAmountCents: 50,
    balanceAfterPoints: 1250,
    balanceAfterUsdCents: 1250,
    transactionDate: "2026-01-20T10:35:00Z",
    description: "Earned from receipt verification",
    receiptId: "rcp-001",
    merchantName: "Target",
    receiptTotal: 1500,
    promotionId: "promo-001",
    promotionName: "Buy 3 Colgate, Get $5",
    metadata: {
      verificationStatus: "approved",
    },
  },
  {
    id: "txn-002",
    accountId: "acc-789xyz",
    programId: "prog-optum-001",
    transactionType: "adjust",
    sourceType: "manual",
    pointsAmount: -100,
    usdAmountCents: -100,
    balanceAfterPoints: 1200,
    balanceAfterUsdCents: 1200,
    transactionDate: "2026-01-18T15:20:00Z",
    description: "Manual adjustment by customer support",
    adjustedByAdministratorId: "admin-001",
    adjustedByName: "jane.smith@kigo.com",
    adjustmentReason: "duplicate_receipt",
    adjustmentNotes:
      "User accidentally submitted same receipt twice. Reversed duplicate points.",
  },
  {
    id: "txn-003",
    accountId: "acc-789xyz",
    programId: "prog-optum-001",
    transactionType: "earn",
    sourceType: "receipt",
    pointsAmount: 100,
    usdAmountCents: 100,
    balanceAfterPoints: 1300,
    balanceAfterUsdCents: 1300,
    transactionDate: "2026-01-15T11:42:00Z",
    description: "Earned from receipt verification",
    receiptId: "rcp-002",
    merchantName: "CVS Pharmacy",
    metadata: {
      verificationStatus: "manual_review",
    },
    receiptTotal: 3550,
    promotionId: "promo-002",
    promotionName: "Wellness Products 10% Back",
  },
  {
    id: "txn-004",
    accountId: "acc-789xyz",
    programId: "prog-optum-001",
    transactionType: "redeem",
    sourceType: "redemption",
    pointsAmount: -500,
    usdAmountCents: -500,
    balanceAfterPoints: 800,
    balanceAfterUsdCents: 800,
    transactionDate: "2026-01-10T09:15:00Z",
    description: "Redeemed for $5 Target gift card",
    metadata: {
      rewardType: "gift_card",
      rewardId: "reward-target-5",
    },
  },
  {
    id: "txn-005",
    accountId: "acc-789xyz",
    programId: "prog-optum-001",
    transactionType: "earn",
    sourceType: "receipt",
    pointsAmount: 200,
    usdAmountCents: 200,
    balanceAfterPoints: 1000,
    balanceAfterUsdCents: 1000,
    transactionDate: "2026-01-05T14:22:00Z",
    description: "Earned from receipt verification",
    receiptId: "rcp-003",
    merchantName: "Walmart",
    receiptTotal: 4250,
  },
];

export const sampleReceipts: Receipt[] = [
  // John Doe - Optum Program Receipts
  {
    id: "rcp-001",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-20T10:34:00Z",
    merchantName: "Target",
    totalAmount: 15.0,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-target.jpg",
    campaignName: "Colgate Triple Bonus",
    actionAmount: 150, // 150 points awarded
    items: [
      {
        name: "Colgate Toothpaste",
        quantity: 3,
        price: 4.99,
        isQualifying: true,
      },
      { name: "Paper Towels", quantity: 1, price: 8.99, isQualifying: false },
    ],
  },
  {
    id: "rcp-002",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-15T11:40:00Z",
    merchantName: "Walgreens",
    totalAmount: 35.5,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-walgreens.jpg",
    campaignName: "Vitamins Bonus Week",
    actionAmount: 200,
    items: [
      { name: "Vitamins", quantity: 2, price: 15.99, isQualifying: true },
      { name: "Band-Aids", quantity: 1, price: 3.49, isQualifying: false },
    ],
  },
  {
    id: "rcp-003",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-18T14:20:00Z",
    merchantName: "Walmart",
    totalAmount: 42.5,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-walmart.jpg",
    campaignName: "Fresh Produce Challenge",
    actionAmount: 300,
    items: [
      { name: "Apples", quantity: 5, price: 7.5, isQualifying: true },
      { name: "Bananas", quantity: 3, price: 4.2, isQualifying: true },
      { name: "Bread", quantity: 2, price: 5.99, isQualifying: false },
    ],
  },
  {
    id: "rcp-004",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-12T16:45:00Z",
    merchantName: "CVS",
    totalAmount: 28.75,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-walgreens-2.jpg",
    campaignName: "Healthy Snacks Promotion",
    actionAmount: 175,
    items: [
      { name: "Protein Bars", quantity: 6, price: 12.99, isQualifying: true },
      { name: "Almonds", quantity: 2, price: 8.99, isQualifying: true },
      { name: "Energy Drink", quantity: 1, price: 2.49, isQualifying: false },
    ],
  },
  {
    id: "rcp-005",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-08T10:30:00Z",
    merchantName: "Kroger",
    totalAmount: 19.99,
    verificationStatus: "rejected",
    imageUrl: "/mock/mock-receipt-costco.jpg",
    campaignName: "Dairy Products Bonus",
    reasonCode: "expired_promotion",
    items: [
      { name: "Milk", quantity: 2, price: 4.99, isQualifying: false },
      { name: "Yogurt", quantity: 4, price: 5.99, isQualifying: false },
    ],
  },
  {
    id: "rcp-006",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-03T08:20:00Z",
    merchantName: "Whole Foods",
    totalAmount: 65.0,
    verificationStatus: "pending",
    imageUrl: "/mock/mock-receipt-bestbuy.jpg",
    campaignName: "Organic Foods Initiative",
    actionAmount: 400,
  },
  {
    id: "rcp-006a",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-05T09:15:00Z",
    merchantName: "Safeway",
    totalAmount: 32.5,
    verificationStatus: "manually_approved",
    imageUrl: "/mock/mock-receipt-target.jpg",
    campaignName: "Health & Wellness",
    actionAmount: 225,
    items: [
      { name: "Multivitamins", quantity: 1, price: 18.99, isQualifying: true },
      { name: "Protein Powder", quantity: 1, price: 13.49, isQualifying: true },
    ],
  },
  {
    id: "rcp-006b",
    accountId: "acc-789xyz-prog-optum-001",
    uploadedAt: "2026-01-02T15:40:00Z",
    merchantName: "Rite Aid",
    totalAmount: 45.0,
    verificationStatus: "manually_rejected",
    imageUrl: "/mock/mock-receipt-walgreens.jpg",
    campaignName: "Seasonal Promotion",
    reasonCode: "receipt_too_old",
    items: [
      { name: "Cold Medicine", quantity: 2, price: 22.49, isQualifying: false },
    ],
  },
  // Sarah Johnson - Optum Program Receipts
  {
    id: "rcp-007",
    accountId: "acc-456abc-prog-optum-001",
    uploadedAt: "2026-01-19T13:25:00Z",
    merchantName: "Target",
    totalAmount: 52.3,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-target.jpg",
    campaignName: "Baby Products Bundle",
    actionAmount: 250,
  },
  {
    id: "rcp-008",
    accountId: "acc-456abc-prog-optum-001",
    uploadedAt: "2026-01-17T09:15:00Z",
    merchantName: "CVS",
    totalAmount: 38.9,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-walgreens-2.jpg",
    campaignName: "Health & Wellness Week",
    actionAmount: 300,
    items: [
      { name: "Vitamins", quantity: 2, price: 18.99, isQualifying: true },
      { name: "Hand Sanitizer", quantity: 3, price: 12.99, isQualifying: true },
    ],
  },
  {
    id: "rcp-009",
    accountId: "acc-456abc-prog-optum-001",
    uploadedAt: "2026-01-14T15:30:00Z",
    merchantName: "Walgreens",
    totalAmount: 28.75,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-walgreens.jpg",
    campaignName: "Diabetes Care Month",
    actionAmount: 175,
  },
  // Michael Chen - Multiple receipts
  {
    id: "rcp-010",
    accountId: "acc-123ghi-prog-optum-001",
    uploadedAt: "2026-01-20T11:00:00Z",
    merchantName: "Walmart",
    totalAmount: 84.5,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-walmart.jpg",
    campaignName: "Healthy Groceries Challenge",
    actionAmount: 450,
    reasonCode: "blurry_image",
  },
  {
    id: "rcp-011",
    accountId: "acc-123ghi-prog-optum-001",
    uploadedAt: "2026-01-18T14:20:00Z",
    merchantName: "Target",
    totalAmount: 62.3,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-target.jpg",
    campaignName: "Fitness Products Promo",
    actionAmount: 350,
  },
  {
    id: "rcp-012",
    accountId: "acc-123ghi-prog-optum-001",
    uploadedAt: "2026-01-16T10:45:00Z",
    merchantName: "Whole Foods",
    totalAmount: 95.2,
    verificationStatus: "rejected",
    imageUrl: "/mock/mock-receipt-bestbuy.jpg",
    campaignName: "Organic Produce Week",
    reasonCode: "ineligible_products",
  },
  // Emily Rodriguez - Various statuses
  {
    id: "rcp-013",
    accountId: "acc-321mno-prog-wellness-002",
    uploadedAt: "2026-01-19T16:00:00Z",
    merchantName: "CVS",
    totalAmount: 45.6,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-walgreens-2.jpg",
    campaignName: "Flu Season Prevention",
    actionAmount: 280,
    reasonCode: "missing_items",
  },
  {
    id: "rcp-014",
    accountId: "acc-321mno-prog-wellness-002",
    uploadedAt: "2026-01-15T12:30:00Z",
    merchantName: "Rite Aid",
    totalAmount: 33.45,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-walgreens.jpg",
    campaignName: "Senior Care Essentials",
    actionAmount: 200,
  },
  {
    id: "rcp-015",
    accountId: "acc-321mno-prog-wellness-002",
    uploadedAt: "2026-01-10T08:15:00Z",
    merchantName: "Kroger",
    totalAmount: 78.9,
    verificationStatus: "pending",
    imageUrl: "/mock/mock-receipt-costco.jpg",
    campaignName: "Heart Healthy Foods",
    actionAmount: 425,
  },
  // Lisa Martinez - Manual review cases
  {
    id: "rcp-016",
    accountId: "acc-789pqr-prog-wellness-002",
    uploadedAt: "2026-01-20T09:30:00Z",
    merchantName: "Target",
    totalAmount: 56.78,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-target.jpg",
    campaignName: "Back to School Health",
    actionAmount: 320,
    reasonCode: "duplicate_submission",
  },
  {
    id: "rcp-017",
    accountId: "acc-789pqr-prog-wellness-002",
    uploadedAt: "2026-01-18T13:45:00Z",
    merchantName: "Walmart",
    totalAmount: 42.3,
    verificationStatus: "manual_review",
    imageUrl: "/mock/mock-receipt-walmart.jpg",
    campaignName: "Immunity Boost Bundle",
    actionAmount: 275,
    reasonCode: "partial_receipt",
  },
  {
    id: "rcp-018",
    accountId: "acc-789pqr-prog-wellness-002",
    uploadedAt: "2026-01-12T11:20:00Z",
    merchantName: "Walgreens",
    totalAmount: 29.99,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-walgreens.jpg",
    campaignName: "Monthly Medication Refill",
    actionAmount: 150,
  },
  // David Kim - Mixed statuses
  {
    id: "rcp-019",
    accountId: "acc-654rst-prog-wellness-002",
    uploadedAt: "2026-01-19T14:50:00Z",
    merchantName: "CVS",
    totalAmount: 67.45,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-walgreens-2.jpg",
    campaignName: "Diabetes Management",
    actionAmount: 380,
  },
  {
    id: "rcp-020",
    accountId: "acc-654rst-prog-wellness-002",
    uploadedAt: "2026-01-16T10:30:00Z",
    merchantName: "Whole Foods",
    totalAmount: 112.3,
    verificationStatus: "approved",
    imageUrl: "/mock/mock-receipt-bestbuy.jpg",
    campaignName: "Clean Eating Challenge",
    actionAmount: 550,
  },
  {
    id: "rcp-021",
    accountId: "acc-654rst-prog-wellness-002",
    uploadedAt: "2026-01-14T09:15:00Z",
    merchantName: "Target",
    totalAmount: 48.6,
    verificationStatus: "rejected",
    imageUrl: "/mock/mock-receipt-target.jpg",
    campaignName: "Fitness January",
    reasonCode: "promotion_expired",
  },
  // Add more receipts for other members
  {
    id: "rcp-022",
    accountId: "acc-456mno-prog-optum-001",
    uploadedAt: "2026-01-20T15:30:00Z",
    merchantName: "Walmart",
    totalAmount: 73.25,
    verificationStatus: "pending",
    imageUrl: "/mock/mock-receipt-walmart.jpg",
    campaignName: "Fresh Start 2026",
    actionAmount: 350,
  },
];

// Database structure: One record per program enrollment
export const sampleMembers: MemberWithPoints[] = [
  // John Doe - Optum enrollment
  {
    id: "member-001-optum",
    email: "john.doe@email.com",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    accountId: "acc-789xyz-prog-optum-001",
    memberSince: "2025-01-15T00:00:00Z",
    phoneNumber: "(555) 123-4567",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 1250,
      currentUsdCents: 1250,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: sampleTransactions,
    totalPointsEarned: 1850,
    totalPointsRedeemed: 500,
    totalAdjustments: -100,
  },
  // John Doe - Wellness enrollment (same person, different program)
  {
    id: "member-001-wellness",
    email: "john.doe@email.com",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    accountId: "acc-789xyz-prog-wellness-001",
    memberSince: "2025-01-15T00:00:00Z",
    phoneNumber: "(555) 123-4567",
    status: "active",
    program: samplePrograms[1],
    pointsBalance: {
      programId: "prog-wellness-001",
      programName: "Wellness Plus",
      currentPoints: 800,
      currentUsdCents: 800,
      conversionRate: 100,
      displayNamePrefix: "WellnessPlus",
      displayName: "Wellness Points",
    },
    transactions: [],
    totalPointsEarned: 800,
    totalPointsRedeemed: 0,
    totalAdjustments: 0,
  },
  // Sarah Johnson - Optum
  {
    id: "member-002-optum",
    email: "sarah.johnson@email.com",
    firstName: "Sarah",
    lastName: "Johnson",
    fullName: "Sarah Johnson",
    accountId: "acc-456abc-prog-optum-001",
    memberSince: "2024-11-20T00:00:00Z",
    phoneNumber: "(555) 987-6543",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 2340,
      currentUsdCents: 2340,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [
      {
        id: "txn-sarah-001",
        accountId: "acc-456abc-prog-optum-001",
        programId: "prog-optum-001",
        transactionType: "earn",
        sourceType: "receipt",
        pointsAmount: 150,
        usdAmountCents: 150,
        balanceAfterPoints: 2340,
        balanceAfterUsdCents: 2340,
        transactionDate: "2026-01-19T13:25:00Z",
        description: "Earned from receipt verification",
        receiptId: "rcp-007",
        merchantName: "Target",
        receiptTotal: 5230,
        metadata: {
          verificationStatus: "approved",
        },
      },
    ],
    totalPointsEarned: 2840,
    totalPointsRedeemed: 500,
    totalAdjustments: 0,
  },
  // Michael Chen - Optum
  {
    id: "member-003-optum",
    email: "michael.chen@email.com",
    firstName: "Michael",
    lastName: "Chen",
    fullName: "Michael Chen",
    accountId: "acc-123def-prog-optum-001",
    memberSince: "2025-02-10T00:00:00Z",
    phoneNumber: "(555) 456-7890",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 875,
      currentUsdCents: 875,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [
      {
        id: "txn-michael-001",
        accountId: "acc-123def-prog-optum-001",
        programId: "prog-optum-001",
        transactionType: "earn",
        sourceType: "receipt",
        pointsAmount: 85,
        usdAmountCents: 85,
        balanceAfterPoints: 875,
        balanceAfterUsdCents: 875,
        transactionDate: "2026-01-18T09:15:00Z",
        description: "Pending verification",
        receiptId: "rcp-michael-001",
        merchantName: "Walgreens",
        receiptTotal: 4250,
        metadata: {
          verificationStatus: "manual_review",
        },
      },
    ],
    totalPointsEarned: 1375,
    totalPointsRedeemed: 500,
    totalAdjustments: 0,
  },
  // Emily Rodriguez - Wellness
  {
    id: "member-004-wellness",
    email: "emily.rodriguez@email.com",
    firstName: "Emily",
    lastName: "Rodriguez",
    fullName: "Emily Rodriguez",
    accountId: "acc-987fed-prog-wellness-001",
    memberSince: "2025-03-05T00:00:00Z",
    phoneNumber: "(555) 234-5678",
    status: "active",
    program: samplePrograms[1],
    pointsBalance: {
      programId: "prog-wellness-001",
      programName: "Wellness Plus",
      currentPoints: 3200,
      currentUsdCents: 3200,
      conversionRate: 100,
      displayNamePrefix: "WellnessPlus",
      displayName: "Wellness Points",
    },
    transactions: [
      {
        id: "txn-emily-001",
        accountId: "acc-987fed-prog-wellness-001",
        programId: "prog-wellness-001",
        transactionType: "earn",
        sourceType: "receipt",
        pointsAmount: 200,
        usdAmountCents: 200,
        balanceAfterPoints: 3200,
        balanceAfterUsdCents: 3200,
        transactionDate: "2026-01-17T14:30:00Z",
        description: "Pending manual review",
        receiptId: "rcp-emily-001",
        merchantName: "Whole Foods",
        receiptTotal: 8750,
        metadata: {
          verificationStatus: "manual_review",
        },
      },
    ],
    totalPointsEarned: 3200,
    totalPointsRedeemed: 0,
    totalAdjustments: 0,
  },
  // David Kim - Optum
  {
    id: "member-005-optum",
    email: "david.kim@email.com",
    firstName: "David",
    lastName: "Kim",
    fullName: "David Kim",
    accountId: "acc-654cba-prog-optum-001",
    memberSince: "2024-12-01T00:00:00Z",
    phoneNumber: "(555) 345-6789",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 1580,
      currentUsdCents: 1580,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [
      {
        id: "txn-david-001",
        accountId: "acc-654cba-prog-optum-001",
        programId: "prog-optum-001",
        transactionType: "earn",
        sourceType: "receipt",
        pointsAmount: 120,
        usdAmountCents: 120,
        balanceAfterPoints: 1580,
        balanceAfterUsdCents: 1580,
        transactionDate: "2026-01-16T10:45:00Z",
        description: "Approved receipt",
        receiptId: "rcp-david-001",
        merchantName: "CVS Pharmacy",
        receiptTotal: 6200,
        metadata: {
          verificationStatus: "approved",
        },
      },
    ],
    totalPointsEarned: 2080,
    totalPointsRedeemed: 500,
    totalAdjustments: 0,
  },
  // Lisa Martinez - Optum
  {
    id: "member-006-optum",
    email: "lisa.martinez@email.com",
    firstName: "Lisa",
    lastName: "Martinez",
    fullName: "Lisa Martinez",
    accountId: "acc-321ghi-prog-optum-001",
    memberSince: "2025-01-28T00:00:00Z",
    phoneNumber: "(555) 456-7891",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 450,
      currentUsdCents: 450,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [
      {
        id: "txn-lisa-001",
        accountId: "acc-321ghi-prog-optum-001",
        programId: "prog-optum-001",
        transactionType: "earn",
        sourceType: "receipt",
        pointsAmount: 75,
        usdAmountCents: 75,
        balanceAfterPoints: 450,
        balanceAfterUsdCents: 450,
        transactionDate: "2026-01-19T16:20:00Z",
        description: "Receipt needs review",
        receiptId: "rcp-lisa-001",
        merchantName: "Rite Aid",
        receiptTotal: 3850,
        metadata: {
          verificationStatus: "manual_review",
        },
      },
    ],
    totalPointsEarned: 450,
    totalPointsRedeemed: 0,
    totalAdjustments: 0,
  },
  // James Wilson - Wellness
  {
    id: "member-007-wellness",
    email: "james.wilson@email.com",
    firstName: "James",
    lastName: "Wilson",
    fullName: "James Wilson",
    accountId: "acc-789jkl-prog-wellness-001",
    memberSince: "2024-10-15T00:00:00Z",
    phoneNumber: "(555) 567-8912",
    status: "inactive",
    program: samplePrograms[1],
    pointsBalance: {
      programId: "prog-wellness-001",
      programName: "Wellness Plus",
      currentPoints: 0,
      currentUsdCents: 0,
      conversionRate: 100,
      displayNamePrefix: "WellnessPlus",
      displayName: "Wellness Points",
    },
    transactions: [],
    totalPointsEarned: 1200,
    totalPointsRedeemed: 1200,
    totalAdjustments: 0,
  },
  // Maria Garcia - Optum
  {
    id: "member-008-optum",
    email: "maria.garcia@email.com",
    firstName: "Maria",
    lastName: "Garcia",
    fullName: "Maria Garcia",
    accountId: "acc-456mno-prog-optum-001",
    memberSince: "2025-02-20T00:00:00Z",
    phoneNumber: "(555) 678-9123",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 5120,
      currentUsdCents: 5120,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [],
    totalPointsEarned: 6120,
    totalPointsRedeemed: 1000,
    totalAdjustments: 0,
  },
  // Robert Taylor - Optum & Wellness (2 records)
  {
    id: "member-009-optum",
    email: "robert.taylor@email.com",
    firstName: "Robert",
    lastName: "Taylor",
    fullName: "Robert Taylor",
    accountId: "acc-123pqr-prog-optum-001",
    memberSince: "2024-09-10T00:00:00Z",
    phoneNumber: "(555) 789-1234",
    status: "active",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 720,
      currentUsdCents: 720,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [],
    totalPointsEarned: 1720,
    totalPointsRedeemed: 1000,
    totalAdjustments: 0,
  },
  {
    id: "member-009-wellness",
    email: "robert.taylor@email.com",
    firstName: "Robert",
    lastName: "Taylor",
    fullName: "Robert Taylor",
    accountId: "acc-123pqr-prog-wellness-001",
    memberSince: "2024-09-10T00:00:00Z",
    phoneNumber: "(555) 789-1234",
    status: "active",
    program: samplePrograms[1],
    pointsBalance: {
      programId: "prog-wellness-001",
      programName: "Wellness Plus",
      currentPoints: 1550,
      currentUsdCents: 1550,
      conversionRate: 100,
      displayNamePrefix: "WellnessPlus",
      displayName: "Wellness Points",
    },
    transactions: [],
    totalPointsEarned: 1550,
    totalPointsRedeemed: 0,
    totalAdjustments: 0,
  },
  // Jennifer Lee - Optum
  {
    id: "member-010-optum",
    email: "jennifer.lee@email.com",
    firstName: "Jennifer",
    lastName: "Lee",
    fullName: "Jennifer Lee",
    accountId: "acc-789stu-prog-optum-001",
    memberSince: "2025-03-12T00:00:00Z",
    phoneNumber: "(555) 891-2345",
    status: "suspended",
    program: samplePrograms[0],
    pointsBalance: {
      programId: "prog-optum-001",
      programName: "Optum HealthyBenefits+",
      currentPoints: 2200,
      currentUsdCents: 2200,
      conversionRate: 100,
      displayNamePrefix: "Optum",
      displayName: "Rewards Points",
    },
    transactions: [],
    totalPointsEarned: 2200,
    totalPointsRedeemed: 0,
    totalAdjustments: 0,
  },
];

// Helper function to find member by search query
export function searchMembers(query: string): MemberWithPoints[] {
  const lowerQuery = query.toLowerCase().trim();

  if (!lowerQuery) {
    return sampleMembers;
  }

  return sampleMembers.filter(
    (member) =>
      member.email.toLowerCase().includes(lowerQuery) ||
      member.fullName.toLowerCase().includes(lowerQuery) ||
      member.accountId.toLowerCase().includes(lowerQuery) ||
      member.firstName.toLowerCase().includes(lowerQuery) ||
      member.lastName.toLowerCase().includes(lowerQuery)
  );
}

// Helper function to get member by ID
export function getMemberById(id: string): MemberWithPoints | undefined {
  return sampleMembers.find((member) => member.id === id);
}

// Helper function to get receipt by ID
export function getReceiptById(id: string): Receipt | undefined {
  return sampleReceipts.find((receipt) => receipt.id === id);
}

// Helper function to get promotion by ID
export function getPromotionById(id: string): Promotion | undefined {
  return samplePromotions.find((promo) => promo.id === id);
}

// Helper function to get promotions by program ID
export function getPromotionsByProgram(programId: string): Promotion[] {
  return samplePromotions.filter(
    (promo) => promo.programId === programId && promo.isActive
  );
}
