/*
 * parity:css. Compiles production's globals.css with production's Tailwind 4
 * engine, then scopes the result so it only applies inside `.pro-root` and so
 * nothing in it can reach the rest of the prototype:
 *
 *  - `@layer` blocks are unwrapped in order. The prototype's Tailwind 3 utilities
 *    are unlayered, and unlayered CSS beats layered CSS regardless of selector,
 *    so the production rules must be unlayered too for `.pro-root .p-6` to win.
 *  - every selector is prefixed with `.pro-root`; `:root`, `html`, `body` and
 *    `:host` become `.pro-root` itself.
 *  - `@property --tw-*` registrations are dropped and Tailwind's own
 *    universal-selector fallback is kept unconditionally. A registered property
 *    is document-global and its `syntax` would invalidate the Tailwind 3 values
 *    the prototype stores in the same `--tw-*` names.
 *  - `@keyframes` are renamed with a `pro-` prefix (keyframe names are global and
 *    the prototype defines `fadeIn` and `slideInRight` too).
 *  - the prototype's own base rules that still reach into `.pro-root` by
 *    inheritance are neutralised on `.pro-root` only.
 *
 * The result is written to public/pro/prod.css and loaded with a <link> tag so
 * Next's CSS pipeline never rewrites it (it would try to resolve the literal
 * `url(...)` production emits for `bg-[url(...)]`, and Turbopack would minify).
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import postcss from "postcss";
import selectorParser from "postcss-selector-parser";

import { PROD_CSS, ROOT } from "./lib.mjs";

const ENTRY = path.join(ROOT, "scripts", "parity", "prod.entry.css");
const SCOPE = ".pro-root";
const ROOT_SELECTORS = new Set([":root", "html", "body", ":host"]);

const compile = () =>
  execFileSync(
    path.join(ROOT, "node_modules", ".bin", "tailwindcss"),
    ["--input", ENTRY, "--output", "-"],
    {
      cwd: ROOT,
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    }
  );

const prefixSelector = (selector) =>
  selectorParser((root) => {
    root.each((sel) => {
      const first = sel.first;
      const text = sel.toString().trim();
      if (ROOT_SELECTORS.has(text)) {
        sel.replaceWith(
          selectorParser
            .selector({ value: "" })
            .append(selectorParser.className({ value: SCOPE.slice(1) }))
        );
        return;
      }
      if (first && first.type === "nesting") return;
      const startsWithRoot = first && ROOT_SELECTORS.has(first.toString());
      if (startsWithRoot) {
        first.replaceWith(selectorParser.className({ value: SCOPE.slice(1) }));
        return;
      }
      sel.prepend(selectorParser.combinator({ value: " " }));
      sel.prepend(selectorParser.className({ value: SCOPE.slice(1) }));
    });
  }).processSync(selector);

const unwrapLayers = (root) => {
  root.walkAtRules("layer", (atRule) => {
    if (atRule.nodes) atRule.replaceWith(atRule.nodes);
    else atRule.remove();
  });
};

const dropPropertyRegistrations = (root) => {
  root.walkAtRules("property", (atRule) => atRule.remove());
  root.walkAtRules("supports", (atRule) => {
    const isPropertyFallback =
      atRule.params.includes("-webkit-hyphens") &&
      atRule.params.includes("margin-trim");
    if (isPropertyFallback) atRule.replaceWith(atRule.nodes);
  });
};

const renameKeyframes = (root) => {
  const names = new Set();
  root.walkAtRules(/^(-webkit-)?keyframes$/, (atRule) => {
    names.add(atRule.params.trim());
    atRule.params = `pro-${atRule.params.trim()}`;
  });
  if (names.size === 0) return;
  const pattern = new RegExp(
    `(^|[\\s,])(${[...names].map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})(?=$|[\\s,;])`,
    "g"
  );
  root.walkDecls((decl) => {
    if (!/^(animation|animation-name|--animate-)/.test(decl.prop)) return;
    decl.value = decl.value.replace(pattern, "$1pro-$2");
  });
};

const scopeSelectors = (root) => {
  root.walkRules((rule) => {
    if (rule.parent?.type === "atrule" && /keyframes$/.test(rule.parent.name))
      return;
    if (rule.parent?.type === "rule") return;
    rule.selector = prefixSelector(rule.selector);
  });
};

const neutraliseHostBase = (root) => {
  root.append(
    postcss
      .rule({ selector: SCOPE })
      .append(
        postcss.decl({ prop: "color", value: "initial" }),
        postcss.decl({ prop: "background-color", value: "transparent" })
      )
  );
};

const main = () => {
  const compiled = compile();
  const root = postcss.parse(compiled);
  unwrapLayers(root);
  dropPropertyRegistrations(root);
  renameKeyframes(root);
  scopeSelectors(root);
  neutraliseHostBase(root);
  const header = `/* Generated by scripts/parity/build-css.mjs. Do not edit; run \`npm run parity:css\`. */\n`;
  fs.mkdirSync(path.dirname(PROD_CSS), { recursive: true });
  fs.writeFileSync(PROD_CSS, header + root.toString());
  const rules = root.nodes.filter((n) => n.type === "rule").length;
  console.log(
    `wrote ${path.relative(ROOT, PROD_CSS)} (${(fs.statSync(PROD_CSS).size / 1024).toFixed(0)} KiB, ${rules} top-level rules)`
  );
};

main();
