import type { Merchant } from "./types";

/**
 * Mock merchant data ported from
 * kigo-demos/public/kigo-pro/index.html (lines 7608-7718).
 *
 * Notes:
 * - The prototype fixture stores offers with a `channel` field
 *   (e.g. "Verizon Value", "JD Perks", "Optum Offers"). In this list-view
 *   port we surface those channels as the offer's distribution publisher
 *   in the Publishers column.
 * - Detail-view fields (status, contact, website, revShare,
 *   supportedOfferTypes, merchantDetail, restrictions, perf, subGroups)
 *   were back-filled to match the prototype's `merchantData` so the
 *   MerchantDetailDialog renders the same content.
 */
export const merchants: Merchant[] = [
  {
    key: "sams",
    name: "Sam's Club",
    id: "MID-10042",
    category: "Retail",
    emoji: "🛒",
    color: "#fff3cd",
    source: "Augeo",
    commissionOffers: true,
    status: "Active",
    contact: "Jennifer Walsh · jwalsh@samsclub.com",
    website: "samsclub.com",
    revShare: "8.5%",
    supportedOfferTypes: [
      "Percentage Off",
      "Free Product",
      "Merchandise",
      "Money Off",
    ],
    merchantDetail:
      "Warehouse club retailer offering bulk groceries, electronics, home goods, and membership-based savings programs.",
    restrictions: [
      { name: "Costco", id: "MID-10088" },
      { name: "BJ's Wholesale", id: "MID-10112" },
    ],
    offers: [
      {
        id: "OID-60000003",
        name: "50% Off Club Membership",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Mar 1, 2026",
        end: "Apr 30, 2026",
        type: "Airdrop",
        offerType: "Percentage Off",
        offerKey: "samsclub",
      },
      {
        id: "OID-55202",
        name: "Free Membership Trial",
        status: "Active",
        channel: "JD Perks",
        publisher: "JD Perks",
        start: "Feb 1, 2026",
        end: "Apr 30, 2026",
        type: "Featured",
        offerType: "Free Product",
        offerKey: "samsclub",
      },
      {
        id: "OID-55203",
        name: "10% off Electronics",
        status: "Planned",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Apr 1, 2026",
        end: "Jun 30, 2026",
        type: "Bundle",
        offerType: "Percentage Off",
        offerKey: "samsclub",
      },
      {
        id: "OID-55100",
        name: "Holiday Gift Set Promo",
        status: "Expired",
        channel: "JD Perks",
        publisher: "JD Perks",
        start: "Nov 1, 2025",
        end: "Dec 31, 2025",
        type: "Airdrop",
        offerType: "Merchandise",
        offerKey: "samsclub",
      },
    ],
    campaigns: [
      {
        id: "CID-3406",
        name: "Welcome Bundle",
        publisher: "Verizon",
        status: "Active",
      },
      {
        id: "CID-3401",
        name: "Monthly Airdrop Bundle",
        publisher: "ampliFI",
        status: "Active",
      },
    ],
    perf: [
      {
        offer: "$20 off $100 Purchase",
        channel: "Verizon Value",
        clicks: 4200,
        saves: 2100,
        redemptions: 680,
        revenue: "$5,780",
      },
      {
        offer: "Free Membership Trial",
        channel: "JD Perks",
        clicks: 1800,
        saves: 920,
        redemptions: 310,
        revenue: "$2,635",
      },
    ],
  },
  {
    key: "disney",
    name: "Disney+",
    id: "MID-10089",
    category: "Entertainment",
    emoji: "🎬",
    color: "#ede9fe",
    source: "EBG",
    commissionOffers: false,
    status: "Attention",
    contact: "Mark Torres · mtorres@disney.com",
    website: "disneyplus.com",
    revShare: "12.0%",
    supportedOfferTypes: [
      "Free Product",
      "Percentage Off",
      "Special Price",
      "ClickThru",
    ],
    merchantDetail:
      "Premium streaming service featuring Disney, Pixar, Marvel, Star Wars, and National Geographic content with bundle options.",
    restrictions: [
      { name: "Netflix", id: "MID-10091" },
      { name: "Hulu", id: "MID-10093" },
      { name: "HBO Max", id: "MID-10095" },
      { name: "Paramount+", id: "MID-10097" },
    ],
    offers: [
      {
        id: "OID-88100",
        name: "Disney+ Bundle — 1 Month Free",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Mar 1, 2026",
        end: "May 31, 2026",
        type: "Airdrop",
        offerType: "Free Product",
        offerKey: "disney",
      },
      {
        id: "OID-88199",
        name: "Disney+ Annual Plan Discount",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Feb 15, 2026",
        end: "Apr 15, 2026",
        type: "Featured",
        offerType: "Percentage Off",
        offerKey: "disney",
      },
      {
        id: "OID-88231",
        name: "Disney+ 3-Month Trial",
        status: "Expired",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Nov 15, 2025",
        end: "Mar 1, 2026",
        type: "Airdrop",
        offerType: "Free Product",
        offerKey: "disney",
      },
    ],
    campaigns: [
      {
        id: "CID-3402",
        name: "Boosted Rewards",
        publisher: "ampliFI",
        status: "Active",
      },
    ],
    perf: [
      {
        offer: "Disney+ Bundle — 1 Month Free",
        channel: "Verizon Value",
        clicks: 9100,
        saves: 5200,
        redemptions: 1840,
        revenue: "$16,560",
      },
      {
        offer: "Disney+ Annual Plan Discount",
        channel: "Verizon Value",
        clicks: 3400,
        saves: 1700,
        redemptions: 520,
        revenue: "$7,800",
      },
    ],
  },
  {
    key: "activefit",
    name: "Active&Fit Direct",
    id: "MID-10156",
    category: "Health & Wellness",
    emoji: "💪",
    color: "#dcfce7",
    source: "Augeo",
    commissionOffers: true,
    status: "Active",
    contact: "Sara Kim · skim@activefit.com",
    website: "activefit.com",
    revShare: "10.0%",
    supportedOfferTypes: ["Free Product", "Percentage Off", "ClickThru"],
    merchantDetail:
      "Fitness membership program offering access to 11,000+ gyms and fitness centers nationwide through employer and health plan benefits.",
    restrictions: [],
    offers: [
      {
        id: "OID-62001",
        name: "Free 30-Day Fitness Pass",
        status: "Active",
        channel: "Optum Offers",
        publisher: "Optum Offers",
        start: "Jan 15, 2026",
        end: "Jun 30, 2026",
        type: "Airdrop",
        offerType: "Free Product",
      },
    ],
    campaigns: [
      {
        id: "CID-3403",
        name: "Welcome Offer — Online Only",
        publisher: "John Deere",
        status: "Active",
      },
      {
        id: "CID-3403",
        name: "Welcome Offer — Online Only",
        publisher: "Everglades",
        status: "Active",
      },
    ],
    perf: [
      {
        offer: "Free 30-Day Fitness Pass",
        channel: "Optum Offers",
        clicks: 2800,
        saves: 1600,
        redemptions: 420,
        revenue: "$4,200",
      },
    ],
  },
  {
    key: "papajohns",
    name: "Papa John's",
    id: "MID-10207",
    category: "Food & Dining",
    emoji: "🍕",
    color: "#fee2e2",
    source: "Direct",
    commissionOffers: false,
    status: "Review",
    contact: "Alex Rivera · arivera@papajohns.com",
    website: "papajohns.com",
    revShare: "7.0%",
    supportedOfferTypes: [
      "Percentage Off",
      "Buy One Get One",
      "Money Off",
      "Free Product",
    ],
    merchantDetail:
      "National pizza delivery and carryout chain known for fresh ingredients and signature garlic sauce.",
    restrictions: [
      { name: "Domino's", id: "MID-10209" },
      { name: "Pizza Hut", id: "MID-10211" },
      { name: "Little Caesars", id: "MID-10213" },
    ],
    isParent: true,
    subGroups: [
      {
        name: "Papa John's — Chicago Metro",
        id: "MID-10207-A",
        contact: "Mike Chen · mchen@papajohns.com",
        status: "Active",
        activeOffers: 1,
        locations: 12,
      },
      {
        name: "Papa John's — Southeast Florida",
        id: "MID-10207-B",
        contact: "Lisa Tran · ltran@papajohns.com",
        status: "Active",
        activeOffers: 2,
        locations: 8,
      },
      {
        name: "Papa John's — Dallas/Fort Worth",
        id: "MID-10207-C",
        contact: "James Ruiz · jruiz@papajohns.com",
        status: "Review",
        activeOffers: 0,
      },
    ],
    offers: [
      {
        id: "OID-71001",
        name: "20% Off Medium Pizza",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Feb 1, 2026",
        end: "Apr 30, 2026",
        type: "Featured",
        offerType: "Percentage Off",
      },
      {
        id: "OID-71002",
        name: "Free Breadsticks with Order",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Mar 1, 2026",
        end: "Mar 31, 2026",
        type: "Bundle",
        offerType: "Buy One Get One",
      },
    ],
    campaigns: [
      {
        id: "CID-3416",
        name: "Mother's Day Bundle",
        publisher: "Verizon",
        status: "Review",
      },
    ],
    perf: [
      {
        offer: "20% Off Medium Pizza",
        channel: "Verizon Value",
        clicks: 5600,
        saves: 3100,
        redemptions: 1200,
        revenue: "$8,400",
      },
      {
        offer: "Free Breadsticks with Order",
        channel: "Verizon Value",
        clicks: 2900,
        saves: 1400,
        redemptions: 680,
        revenue: "$3,400",
      },
    ],
  },
  {
    key: "amazon",
    name: "Amazon",
    id: "MID-10331",
    category: "Retail",
    emoji: "📦",
    color: "#fef3c7",
    source: "Augeo",
    commissionOffers: true,
    status: "Active",
    contact: "Chris Lee · clee@amazon.com",
    website: "amazon.com",
    revShare: "9.0%",
    supportedOfferTypes: [
      "Cash Back",
      "Percentage Off",
      "Free Product",
      "Spend and Get",
      "Digital Gift Card",
    ],
    merchantDetail:
      "Global e-commerce marketplace offering electronics, household goods, groceries, streaming, and cloud services with Prime membership benefits.",
    restrictions: [
      { name: "Walmart", id: "MID-10333" },
      { name: "Target", id: "MID-10335" },
    ],
    offers: [
      {
        id: "OID-95001",
        name: "$15 off First Prime Purchase",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Jan 1, 2026",
        end: "Mar 31, 2026",
        type: "Airdrop",
        offerType: "Cash Back",
      },
      {
        id: "OID-95002",
        name: "Prime Video 3-Month Free Trial",
        status: "Active",
        channel: "JD Perks",
        publisher: "JD Perks",
        start: "Feb 1, 2026",
        end: "May 31, 2026",
        type: "Featured",
        offerType: "Free Product",
      },
      {
        id: "OID-95003",
        name: "20% off Amazon Fresh",
        status: "Active",
        channel: "Optum Offers",
        publisher: "Optum Offers",
        start: "Mar 1, 2026",
        end: "Jun 30, 2026",
        type: "Airdrop",
        offerType: "Percentage Off",
      },
      {
        id: "OID-95004",
        name: "Alexa Device Bundle Offer",
        status: "Active",
        channel: "Verizon Value",
        publisher: "Verizon Value",
        start: "Mar 15, 2026",
        end: "Apr 30, 2026",
        type: "Bundle",
        offerType: "Spend and Get",
      },
    ],
    campaigns: [
      {
        id: "CID-3401",
        name: "Monthly Airdrop Bundle",
        publisher: "ampliFI",
        status: "Active",
      },
      {
        id: "CID-3405",
        name: "Commodity Classic Event",
        publisher: "John Deere",
        status: "Review",
      },
      {
        id: "CID-3416",
        name: "Mother's Day Bundle",
        publisher: "Verizon",
        status: "Review",
      },
    ],
    perf: [
      {
        offer: "$15 off First Prime Purchase",
        channel: "Verizon Value",
        clicks: 12400,
        saves: 7200,
        redemptions: 2800,
        revenue: "$42,000",
      },
      {
        offer: "Prime Video 3-Month Free Trial",
        channel: "JD Perks",
        clicks: 4100,
        saves: 2400,
        redemptions: 820,
        revenue: "$12,300",
      },
      {
        offer: "20% off Amazon Fresh",
        channel: "Optum Offers",
        clicks: 3200,
        saves: 1900,
        redemptions: 640,
        revenue: "$9,600",
      },
    ],
  },
];
