/* Generated by scripts/parity/sync-prod.mjs from scripts/parity/manifest.json. Do not edit. */
import type { ParityStory } from "./story-frame";

import * as stories0 from "@/components/prod/badge/badge.stories";
import * as stories1 from "@/components/prod/card/card.stories";
import * as stories2 from "@/components/prod/button/button.stories";
import * as stories3 from "@/components/prod/tooltip/tooltip.stories";
import * as stories4 from "@/components/prod/input/input.stories";
import * as stories5 from "@/components/prod/search-bar/search-bar.stories";
import * as stories6 from "@/components/prod/data-table/data-table.stories";
import * as stories7 from "@/components/prod/table/table.stories";
import * as stories8 from "@/components/prod/dialog/dialog.stories";
import * as stories9 from "@/components/prod/tabs/tabs.stories";
import * as stories10 from "@/components/prod/skeleton/skeleton.stories";
import * as stories11 from "@/components/prod/loader/loader.stories";
import * as stories12 from "@/components/prod/toast/toast.stories";
import * as stories13 from "@/components/prod/page-header/page-header.stories";
import * as stories14 from "@/components/prod/breadcrumbs/breadcrumbs.stories";
import * as stories15 from "@/components/prod/header/header.stories";
import * as stories16 from "@/components/prod/sidebar/sidebar.stories";
import * as stories18 from "@/components/prod/shell/app-shell.stories";

const registry: Record<string, ParityStory> = {
  "components-badge--default": {
    meta: stories0.default,
    story: stories0.Default,
  },
  "components-badge--primary": {
    meta: stories0.default,
    story: stories0.Primary,
  },
  "components-badge--secondary": {
    meta: stories0.default,
    story: stories0.Secondary,
  },
  "components-badge--destructive": {
    meta: stories0.default,
    story: stories0.Destructive,
  },
  "components-badge--success": {
    meta: stories0.default,
    story: stories0.Success,
  },
  "components-badge--warning": {
    meta: stories0.default,
    story: stories0.Warning,
  },
  "components-badge--info": { meta: stories0.default, story: stories0.Info },
  "components-badge--neutral": {
    meta: stories0.default,
    story: stories0.Neutral,
  },
  "components-badge--size-default": {
    meta: stories0.default,
    story: stories0.SizeDefault,
  },
  "components-badge--size-small": {
    meta: stories0.default,
    story: stories0.SizeSmall,
  },
  "components-badge--size-extra-small": {
    meta: stories0.default,
    story: stories0.SizeExtraSmall,
  },
  "components-badge--roundness-default": {
    meta: stories0.default,
    story: stories0.RoundnessDefault,
  },
  "components-badge--roundness-medium": {
    meta: stories0.default,
    story: stories0.RoundnessMedium,
  },
  "components-badge--roundness-small": {
    meta: stories0.default,
    story: stories0.RoundnessSmall,
  },
  "components-badge--roundness-none": {
    meta: stories0.default,
    story: stories0.RoundnessNone,
  },
  "components-badge--outline": {
    meta: stories0.default,
    story: stories0.Outline,
  },
  "components-badge--outline-destructive": {
    meta: stories0.default,
    story: stories0.OutlineDestructive,
  },
  "components-badge--outline-success": {
    meta: stories0.default,
    story: stories0.OutlineSuccess,
  },
  "components-badge--all-variants": {
    meta: stories0.default,
    story: stories0.AllVariants,
  },
  "components-card--default": {
    meta: stories1.default,
    story: stories1.Default,
  },
  "components-card--elevation-2": {
    meta: stories1.default,
    story: stories1.Elevation2,
  },
  "components-card--elevation-3": {
    meta: stories1.default,
    story: stories1.Elevation3,
  },
  "components-card--elevation-4": {
    meta: stories1.default,
    story: stories1.Elevation4,
  },
  "components-card--roundness-large": {
    meta: stories1.default,
    story: stories1.RoundnessLarge,
  },
  "components-card--all-elevations": {
    meta: stories1.default,
    story: stories1.AllElevations,
  },
  "components-button--default": {
    meta: stories2.default,
    story: stories2.Default,
  },
  "components-button--primary": {
    meta: stories2.default,
    story: stories2.Primary,
  },
  "components-button--secondary": {
    meta: stories2.default,
    story: stories2.Secondary,
  },
  "components-button--destructive": {
    meta: stories2.default,
    story: stories2.Destructive,
  },
  "components-button--ghost": { meta: stories2.default, story: stories2.Ghost },
  "components-button--link": { meta: stories2.default, story: stories2.Link },
  "components-button--outline": {
    meta: stories2.default,
    story: stories2.Outline,
  },
  "components-button--outline-destructive": {
    meta: stories2.default,
    story: stories2.OutlineDestructive,
  },
  "components-button--ghost-destructive": {
    meta: stories2.default,
    story: stories2.GhostDestructive,
  },
  "components-button--link-destructive": {
    meta: stories2.default,
    story: stories2.LinkDestructive,
  },
  "components-button--with-icon": {
    meta: stories2.default,
    story: stories2.WithIcon,
  },
  "components-button--icon-only": {
    meta: stories2.default,
    story: stories2.IconOnly,
  },
  "components-button--disabled": {
    meta: stories2.default,
    story: stories2.Disabled,
  },
  "components-button--size-extra-small": {
    meta: stories2.default,
    story: stories2.SizeExtraSmall,
  },
  "components-button--size-small": {
    meta: stories2.default,
    story: stories2.SizeSmall,
  },
  "components-button--size-large": {
    meta: stories2.default,
    story: stories2.SizeLarge,
  },
  "components-button--size-extra-large": {
    meta: stories2.default,
    story: stories2.SizeExtraLarge,
  },
  "components-button--all-variants": {
    meta: stories2.default,
    story: stories2.AllVariants,
  },
  "components-tooltip--default": {
    meta: stories3.default,
    story: stories3.Default,
  },
  "components-tooltip--top": { meta: stories3.default, story: stories3.Top },
  "components-tooltip--right": {
    meta: stories3.default,
    story: stories3.Right,
  },
  "components-tooltip--bottom": {
    meta: stories3.default,
    story: stories3.Bottom,
  },
  "components-tooltip--left": { meta: stories3.default, story: stories3.Left },
  "components-tooltip--with-rich-content": {
    meta: stories3.default,
    story: stories3.WithRichContent,
  },
  "components-tooltip--all-sides": {
    meta: stories3.default,
    story: stories3.AllSides,
  },
  "components-input--default": {
    meta: stories4.default,
    story: stories4.Default,
  },
  "components-input--with-value": {
    meta: stories4.default,
    story: stories4.WithValue,
  },
  "components-input--disabled": {
    meta: stories4.default,
    story: stories4.Disabled,
  },
  "components-input--with-label": {
    meta: stories4.default,
    story: stories4.WithLabel,
  },
  "components-input--password": {
    meta: stories4.default,
    story: stories4.Password,
  },
  "components-input--file": { meta: stories4.default, story: stories4.File },
  "components-search-bar--default": {
    meta: stories5.default,
    story: stories5.Default,
  },
  "components-search-bar--custom-placeholder": {
    meta: stories5.default,
    story: stories5.CustomPlaceholder,
  },
  "components-search-bar--with-existing-query": {
    meta: stories5.default,
    story: stories5.WithExistingQuery,
  },
  "components-search-bar--disabled": {
    meta: stories5.default,
    story: stories5.Disabled,
  },
  "components-data-table--default": {
    meta: stories6.default,
    story: stories6.Default,
  },
  "components-data-table--without-pagination": {
    meta: stories6.default,
    story: stories6.WithoutPagination,
  },
  "components-data-table--empty": {
    meta: stories6.default,
    story: stories6.Empty,
  },
  "components-data-table--custom-empty-message": {
    meta: stories6.default,
    story: stories6.CustomEmptyMessage,
  },
  "components-table--default": {
    meta: stories7.default,
    story: stories7.Default,
  },
  "components-table--simple": {
    meta: stories7.default,
    story: stories7.Simple,
  },
  "components-table--empty": { meta: stories7.default, story: stories7.Empty },
  "components-dialog--default": {
    meta: stories8.default,
    story: stories8.Default,
  },
  "components-dialog--with-form": {
    meta: stories8.default,
    story: stories8.WithForm,
  },
  "components-dialog--controlled": {
    meta: stories8.default,
    story: stories8.Controlled,
  },
  "components-dialog--without-close-button": {
    meta: stories8.default,
    story: stories8.WithoutCloseButton,
  },
  "components-tabs--default": {
    meta: stories9.default,
    story: stories9.Default,
  },
  "components-tabs--two-tabs": {
    meta: stories9.default,
    story: stories9.TwoTabs,
  },
  "components-tabs--with-disabled-tab": {
    meta: stories9.default,
    story: stories9.WithDisabledTab,
  },
  "components-skeleton--default": {
    meta: stories10.default,
    story: stories10.Default,
  },
  "components-skeleton--circle": {
    meta: stories10.default,
    story: stories10.Circle,
  },
  "components-skeleton--card": {
    meta: stories10.default,
    story: stories10.Card,
  },
  "components-skeleton--form-skeleton": {
    meta: stories10.default,
    story: stories10.FormSkeleton,
  },
  "components-loader--default": {
    meta: stories11.default,
    story: stories11.Default,
  },
  "components-loader--large": {
    meta: stories11.default,
    story: stories11.Large,
  },
  "components-loader--extra-large": {
    meta: stories11.default,
    story: stories11.ExtraLarge,
  },
  "components-loader--all-sizes": {
    meta: stories11.default,
    story: stories11.AllSizes,
  },
  "components-toast--default": {
    meta: stories12.default,
    story: stories12.Default,
  },
  "components-toast--with-description": {
    meta: stories12.default,
    story: stories12.WithDescription,
  },
  "components-toast--with-action": {
    meta: stories12.default,
    story: stories12.WithAction,
  },
  "components-toast--with-description-and-action": {
    meta: stories12.default,
    story: stories12.WithDescriptionAndAction,
  },
  "components-toast--destructive": {
    meta: stories12.default,
    story: stories12.Destructive,
  },
  "components-toast--destructive-with-action": {
    meta: stories12.default,
    story: stories12.DestructiveWithAction,
  },
  "components-toast--success": {
    meta: stories12.default,
    story: stories12.Success,
  },
  "components-toast--success-with-action": {
    meta: stories12.default,
    story: stories12.SuccessWithAction,
  },
  "components-toast--warning": {
    meta: stories12.default,
    story: stories12.Warning,
  },
  "components-toast--warning-with-action": {
    meta: stories12.default,
    story: stories12.WarningWithAction,
  },
  "components-toast--multiple-toasts": {
    meta: stories12.default,
    story: stories12.MultipleToasts,
  },
  "components-toast--custom-duration": {
    meta: stories12.default,
    story: stories12.CustomDuration,
  },
  "components-toast--all-variants": {
    meta: stories12.default,
    story: stories12.AllVariants,
  },
  "app-protected-components-page-header--default": {
    meta: stories13.default,
    story: stories13.Default,
  },
  "app-protected-components-page-header--with-actions": {
    meta: stories13.default,
    story: stories13.WithActions,
  },
  "app-protected-components-page-header--with-custom-emoji": {
    meta: stories13.default,
    story: stories13.WithCustomEmoji,
  },
  "app-protected-components-page-header--with-custom-gradient": {
    meta: stories13.default,
    story: stories13.WithCustomGradient,
  },
  "app-protected-components-page-header--aurora-variant": {
    meta: stories13.default,
    story: stories13.AuroraVariant,
  },
  "app-protected-components-page-header--all-variants": {
    meta: stories13.default,
    story: stories13.AllVariants,
  },
  "app-protected-components-breadcrumbs--dashboard": {
    meta: stories14.default,
    story: stories14.Dashboard,
  },
  "app-protected-components-breadcrumbs--single-level": {
    meta: stories14.default,
    story: stories14.SingleLevel,
  },
  "app-protected-components-breadcrumbs--two-levels": {
    meta: stories14.default,
    story: stories14.TwoLevels,
  },
  "app-protected-components-breadcrumbs--three-levels": {
    meta: stories14.default,
    story: stories14.ThreeLevels,
  },
  "app-protected-components-breadcrumbs--with-non-navigable-wrapper": {
    meta: stories14.default,
    story: stories14.WithNonNavigableWrapper,
  },
  "app-protected-components-header--admin": {
    meta: stories15.default,
    story: stories15.Admin,
  },
  "app-protected-components-sidebar--admin-expanded": {
    meta: stories16.default,
    story: stories16.AdminExpanded,
  },
  "app-protected-components-sidebar--admin-collapsed": {
    meta: stories16.default,
    story: stories16.AdminCollapsed,
  },
  "app-protected-components-sidebar--modules-group-collapsed": {
    meta: stories16.default,
    story: stories16.ModulesGroupCollapsed,
  },
  "app-protected-components-sidebar--tools-group-collapsed": {
    meta: stories16.default,
    story: stories16.ToolsGroupCollapsed,
  },
  "app-protected-components-sidebar--all-groups-collapsed": {
    meta: stories16.default,
    story: stories16.AllGroupsCollapsed,
  },
  "app-protected-components-app-shell--support-manager": {
    meta: stories18.default,
    story: stories18.SupportManager,
  },
};

export { registry };
