import { OfferStatus, OfferType } from "@/types/offers";

export interface OfferListItem {
  id: string;
  offerName: string;
  merchantName: string;
  merchantId: string;
  offerType: OfferType;
  offerStatus: OfferStatus;
  redemptions: number;
  endDate: string; // ISO date string
}

export const STATUS_LABELS: Record<OfferStatus, string> = {
  published: "Published",
  draft: "Inactive",
  expired: "Inactive",
  archived: "Inactive",
};

export const OFFER_TYPE_LABELS: Record<OfferType, string> = {
  bogo: "Buy One Get One",
  percentage_savings: "Percentage Off",
  dollars_off: "Dollars Off",
  cashback: "Cashback",
  free_with_purchase: "Free with Purchase",
  price_point: "Fixed Price",
  clickthrough: "Clickthrough",
  loyalty_points: "Loyalty Points",
  spend_and_get: "Spend & Get",
};

export const MOCK_MERCHANTS = [
  { id: "m1", name: "Pizza Palace" },
  { id: "m2", name: "Coffee Corner" },
  { id: "m3", name: "Burger Barn" },
  { id: "m4", name: "Taco Town" },
  { id: "m5", name: "Sushi Station" },
  { id: "m6", name: "Pasta Place" },
  { id: "m7", name: "Smoothie Stop" },
  { id: "m8", name: "Bakery Bliss" },
  { id: "m9", name: "Green Leaf Grocery" },
  { id: "m10", name: "Fitness First Gym" },
  { id: "m11", name: "AutoZone Express" },
  { id: "m12", name: "Pet Paradise" },
  { id: "m13", name: "Sunny Side Diner" },
  { id: "m14", name: "TechHub Electronics" },
  { id: "m15", name: "Blossom Florist" },
  { id: "m16", name: "Golden Wok" },
  { id: "m17", name: "Mountain Brew Co." },
  { id: "m18", name: "Fresh Cuts Barber" },
  { id: "m19", name: "Lakeside Pharmacy" },
  { id: "m20", name: "Urban Threads Apparel" },
  { id: "m21", name: "Campfire Grill" },
  { id: "m22", name: "Bella Nail Studio" },
  { id: "m23", name: "QuickFix Auto Repair" },
  { id: "m24", name: "Horizon Travel Agency" },
  { id: "m25", name: "Maple Street Books" },
];

export const MOCK_OFFERS: OfferListItem[] = [
  // --- Pizza Palace (m1) ---
  {
    id: "OFF-001",
    offerName: "50% Off Large Pizza",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 1243,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-010",
    offerName: "30% Off Party Platter",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 189,
    endDate: "2026-07-15",
  },
  {
    id: "OFF-017",
    offerName: "Family Pizza Bundle",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "price_point",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-08-01",
  },
  {
    id: "OFF-026",
    offerName: "Free Garlic Bread with XL",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 876,
    endDate: "2026-09-15",
  },
  {
    id: "OFF-027",
    offerName: "Pizza Palace Loyalty Stars",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 3410,
    endDate: "2026-12-31",
  },

  // --- Coffee Corner (m2) ---
  {
    id: "OFF-002",
    offerName: "Buy One Get One Latte",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 892,
    endDate: "2026-05-15",
  },
  {
    id: "OFF-012",
    offerName: "Shop & Save $25 Reward",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "spend_and_get",
    offerStatus: "published",
    redemptions: 756,
    endDate: "2026-06-15",
  },
  {
    id: "OFF-018",
    offerName: "Espresso Loyalty Points",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "loyalty_points",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-025",
    offerName: "Morning Coffee Clickthrough",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "clickthrough",
    offerStatus: "archived",
    redemptions: 2345,
    endDate: "2025-08-31",
  },
  {
    id: "OFF-028",
    offerName: "$3 Off Cold Brew",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 1102,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-029",
    offerName: "Free Pastry with Any Drink",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 2034,
    endDate: "2026-07-01",
  },

  // --- Burger Barn (m3) ---
  {
    id: "OFF-003",
    offerName: "$5 Off Double Burger",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "dollars_off",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-07-01",
  },
  {
    id: "OFF-013",
    offerName: "Online Order Redirect",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 3200,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-024",
    offerName: "Slider Sampler Special",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "price_point",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-030",
    offerName: "BOGO Cheeseburger Fridays",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 1560,
    endDate: "2026-10-31",
  },

  // --- Taco Town (m4) ---
  {
    id: "OFF-004",
    offerName: "Free Chips with Combo",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 567,
    endDate: "2026-04-30",
  },
  {
    id: "OFF-009",
    offerName: "BOGO Breakfast Burrito",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "bogo",
    offerStatus: "archived",
    redemptions: 432,
    endDate: "2025-11-30",
  },
  {
    id: "OFF-019",
    offerName: "Taco Tuesday $2 Tacos",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 4521,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-031",
    offerName: "10% Cashback on Burritos",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "cashback",
    offerStatus: "published",
    redemptions: 789,
    endDate: "2026-09-01",
  },
  {
    id: "OFF-032",
    offerName: "Nacho Fiesta Platter $7.99",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "price_point",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-11-01",
  },

  // --- Sushi Station (m5) ---
  {
    id: "OFF-005",
    offerName: "20% Off Sashimi Platter",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "percentage_savings",
    offerStatus: "expired",
    redemptions: 345,
    endDate: "2025-12-31",
  },
  {
    id: "OFF-014",
    offerName: "Happy Hour BOGO Rolls",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 678,
    endDate: "2026-05-31",
  },
  {
    id: "OFF-023",
    offerName: "Sushi Date Night Deal",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "spend_and_get",
    offerStatus: "published",
    redemptions: 145,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-033",
    offerName: "Omakase Chef's Special $49",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 92,
    endDate: "2026-08-15",
  },

  // --- Pasta Place (m6) ---
  {
    id: "OFF-006",
    offerName: "Lunch Special $9.99",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 2100,
    endDate: "2026-08-15",
  },
  {
    id: "OFF-011",
    offerName: "$10 Off Dinner for Two",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "dollars_off",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-10-01",
  },
  {
    id: "OFF-020",
    offerName: "Weekend Brunch Cashback",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "cashback",
    offerStatus: "archived",
    redemptions: 312,
    endDate: "2025-10-31",
  },
  {
    id: "OFF-034",
    offerName: "Pasta Place Rewards Program",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 1845,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-035",
    offerName: "15% Off Catering Orders",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 67,
    endDate: "2026-11-30",
  },

  // --- Smoothie Stop (m7) ---
  {
    id: "OFF-007",
    offerName: "5% Cashback on Smoothies",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "cashback",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-09-01",
  },
  {
    id: "OFF-015",
    offerName: "Summer Smoothie Special",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "price_point",
    offerStatus: "expired",
    redemptions: 1890,
    endDate: "2025-09-15",
  },
  {
    id: "OFF-021",
    offerName: "Protein Boost Add-On",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-04-15",
  },
  {
    id: "OFF-036",
    offerName: "Acai Bowl BOGO Weekends",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 412,
    endDate: "2026-06-30",
  },

  // --- Bakery Bliss (m8) ---
  {
    id: "OFF-008",
    offerName: "Free Cookie with Purchase",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 1567,
    endDate: "2026-03-31",
  },
  {
    id: "OFF-016",
    offerName: "Birthday Cake Discount",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 234,
    endDate: "2026-11-30",
  },
  {
    id: "OFF-022",
    offerName: "Holiday Cookie Box",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "dollars_off",
    offerStatus: "expired",
    redemptions: 567,
    endDate: "2025-12-25",
  },
  {
    id: "OFF-037",
    offerName: "Wedding Cake Consultation Click",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-038",
    offerName: "Croissant Club Loyalty",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 2310,
    endDate: "2026-12-31",
  },

  // --- Green Leaf Grocery (m9) ---
  {
    id: "OFF-039",
    offerName: "10% Off Organic Produce",
    merchantName: "Green Leaf Grocery",
    merchantId: "m9",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 3456,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-040",
    offerName: "$15 Off Orders Over $100",
    merchantName: "Green Leaf Grocery",
    merchantId: "m9",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 1289,
    endDate: "2026-07-15",
  },
  {
    id: "OFF-041",
    offerName: "Free Reusable Bag with $50+",
    merchantName: "Green Leaf Grocery",
    merchantId: "m9",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 678,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-042",
    offerName: "Green Leaf Weekly Deals Click",
    merchantName: "Green Leaf Grocery",
    merchantId: "m9",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 5432,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-043",
    offerName: "Grocery Rewards Points",
    merchantName: "Green Leaf Grocery",
    merchantId: "m9",
    offerType: "loyalty_points",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-12-31",
  },

  // --- Fitness First Gym (m10) ---
  {
    id: "OFF-044",
    offerName: "First Month 50% Off",
    merchantName: "Fitness First Gym",
    merchantId: "m10",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-045",
    offerName: "BOGO Personal Training Session",
    merchantName: "Fitness First Gym",
    merchantId: "m10",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 234,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-046",
    offerName: "Annual Membership $299",
    merchantName: "Fitness First Gym",
    merchantId: "m10",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 156,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-047",
    offerName: "Refer-a-Friend $20 Cashback",
    merchantName: "Fitness First Gym",
    merchantId: "m10",
    offerType: "cashback",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-10-01",
  },

  // --- AutoZone Express (m11) ---
  {
    id: "OFF-048",
    offerName: "$20 Off Oil Change",
    merchantName: "AutoZone Express",
    merchantId: "m11",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 2345,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-049",
    offerName: "Free Tire Rotation with Service",
    merchantName: "AutoZone Express",
    merchantId: "m11",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 1456,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-050",
    offerName: "15% Off All Accessories",
    merchantName: "AutoZone Express",
    merchantId: "m11",
    offerType: "percentage_savings",
    offerStatus: "expired",
    redemptions: 789,
    endDate: "2025-11-30",
  },
  {
    id: "OFF-051",
    offerName: "AutoZone Rewards Points",
    merchantName: "AutoZone Express",
    merchantId: "m11",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 4567,
    endDate: "2026-12-31",
  },

  // --- Pet Paradise (m12) ---
  {
    id: "OFF-052",
    offerName: "BOGO Dog Treats",
    merchantName: "Pet Paradise",
    merchantId: "m12",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 1234,
    endDate: "2026-08-15",
  },
  {
    id: "OFF-053",
    offerName: "$10 Off First Grooming",
    merchantName: "Pet Paradise",
    merchantId: "m12",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 567,
    endDate: "2026-07-01",
  },
  {
    id: "OFF-054",
    offerName: "Pet Supplies Clickthrough",
    merchantName: "Pet Paradise",
    merchantId: "m12",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 3890,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-055",
    offerName: "Puppy Starter Kit $29.99",
    merchantName: "Pet Paradise",
    merchantId: "m12",
    offerType: "price_point",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-10-15",
  },

  // --- Sunny Side Diner (m13) ---
  {
    id: "OFF-056",
    offerName: "Breakfast Combo $6.99",
    merchantName: "Sunny Side Diner",
    merchantId: "m13",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 5678,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-057",
    offerName: "Free Coffee with Breakfast",
    merchantName: "Sunny Side Diner",
    merchantId: "m13",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 3421,
    endDate: "2026-05-31",
  },
  {
    id: "OFF-058",
    offerName: "Sunday Brunch 20% Off",
    merchantName: "Sunny Side Diner",
    merchantId: "m13",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 1234,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-059",
    offerName: "Diner Loyalty Card",
    merchantName: "Sunny Side Diner",
    merchantId: "m13",
    offerType: "loyalty_points",
    offerStatus: "archived",
    redemptions: 8901,
    endDate: "2025-12-31",
  },

  // --- TechHub Electronics (m14) ---
  {
    id: "OFF-060",
    offerName: "25% Off Headphones",
    merchantName: "TechHub Electronics",
    merchantId: "m14",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 456,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-061",
    offerName: "$50 Off Laptops Over $500",
    merchantName: "TechHub Electronics",
    merchantId: "m14",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 234,
    endDate: "2026-07-15",
  },
  {
    id: "OFF-062",
    offerName: "Free Screen Protector with Phone",
    merchantName: "TechHub Electronics",
    merchantId: "m14",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 1890,
    endDate: "2026-10-31",
  },
  {
    id: "OFF-063",
    offerName: "TechHub Cashback Program",
    merchantName: "TechHub Electronics",
    merchantId: "m14",
    offerType: "cashback",
    offerStatus: "published",
    redemptions: 678,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-064",
    offerName: "Refurbished Deals Clickthrough",
    merchantName: "TechHub Electronics",
    merchantId: "m14",
    offerType: "clickthrough",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-09-01",
  },

  // --- Blossom Florist (m15) ---
  {
    id: "OFF-065",
    offerName: "Valentine's Bouquet $29.99",
    merchantName: "Blossom Florist",
    merchantId: "m15",
    offerType: "price_point",
    offerStatus: "expired",
    redemptions: 2340,
    endDate: "2026-02-14",
  },
  {
    id: "OFF-066",
    offerName: "15% Off Wedding Arrangements",
    merchantName: "Blossom Florist",
    merchantId: "m15",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 123,
    endDate: "2026-11-30",
  },
  {
    id: "OFF-067",
    offerName: "Free Vase with Deluxe Bouquet",
    merchantName: "Blossom Florist",
    merchantId: "m15",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 456,
    endDate: "2026-08-15",
  },

  // --- Golden Wok (m16) ---
  {
    id: "OFF-068",
    offerName: "BOGO Spring Rolls",
    merchantName: "Golden Wok",
    merchantId: "m16",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 1567,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-069",
    offerName: "Family Dinner $39.99",
    merchantName: "Golden Wok",
    merchantId: "m16",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-070",
    offerName: "Spend $50 Get $10 Back",
    merchantName: "Golden Wok",
    merchantId: "m16",
    offerType: "spend_and_get",
    offerStatus: "published",
    redemptions: 345,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-071",
    offerName: "Wok Rewards Loyalty",
    merchantName: "Golden Wok",
    merchantId: "m16",
    offerType: "loyalty_points",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-12-31",
  },

  // --- Mountain Brew Co. (m17) ---
  {
    id: "OFF-072",
    offerName: "Craft Beer Flight $12.99",
    merchantName: "Mountain Brew Co.",
    merchantId: "m17",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 1234,
    endDate: "2026-10-31",
  },
  {
    id: "OFF-073",
    offerName: "BOGO Pints on Tap",
    merchantName: "Mountain Brew Co.",
    merchantId: "m17",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 2345,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-074",
    offerName: "Brewery Tour Clickthrough",
    merchantName: "Mountain Brew Co.",
    merchantId: "m17",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 678,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-075",
    offerName: "5% Cashback on Growler Fills",
    merchantName: "Mountain Brew Co.",
    merchantId: "m17",
    offerType: "cashback",
    offerStatus: "published",
    redemptions: 456,
    endDate: "2026-09-15",
  },

  // --- Fresh Cuts Barber (m18) ---
  {
    id: "OFF-076",
    offerName: "$5 Off First Haircut",
    merchantName: "Fresh Cuts Barber",
    merchantId: "m18",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-077",
    offerName: "Free Beard Trim with Haircut",
    merchantName: "Fresh Cuts Barber",
    merchantId: "m18",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 567,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-078",
    offerName: "Fresh Cuts Loyalty Stamps",
    merchantName: "Fresh Cuts Barber",
    merchantId: "m18",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 1234,
    endDate: "2026-12-31",
  },

  // --- Lakeside Pharmacy (m19) ---
  {
    id: "OFF-079",
    offerName: "20% Off Vitamins & Supplements",
    merchantName: "Lakeside Pharmacy",
    merchantId: "m19",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 2345,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-080",
    offerName: "$10 Off Prescriptions Over $50",
    merchantName: "Lakeside Pharmacy",
    merchantId: "m19",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 1678,
    endDate: "2026-10-31",
  },
  {
    id: "OFF-081",
    offerName: "Flu Shot Cashback $5",
    merchantName: "Lakeside Pharmacy",
    merchantId: "m19",
    offerType: "cashback",
    offerStatus: "expired",
    redemptions: 3456,
    endDate: "2025-12-31",
  },
  {
    id: "OFF-082",
    offerName: "Pharmacy Rewards Program",
    merchantName: "Lakeside Pharmacy",
    merchantId: "m19",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 5678,
    endDate: "2026-12-31",
  },

  // --- Urban Threads Apparel (m20) ---
  {
    id: "OFF-083",
    offerName: "30% Off Summer Collection",
    merchantName: "Urban Threads Apparel",
    merchantId: "m20",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 1890,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-084",
    offerName: "BOGO Graphic Tees",
    merchantName: "Urban Threads Apparel",
    merchantId: "m20",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 2345,
    endDate: "2026-07-15",
  },
  {
    id: "OFF-085",
    offerName: "Free Tote with $75+ Purchase",
    merchantName: "Urban Threads Apparel",
    merchantId: "m20",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 456,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-086",
    offerName: "Clearance Rack Clickthrough",
    merchantName: "Urban Threads Apparel",
    merchantId: "m20",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 6789,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-087",
    offerName: "Spend $100 Get $20 Gift Card",
    merchantName: "Urban Threads Apparel",
    merchantId: "m20",
    offerType: "spend_and_get",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-11-01",
  },

  // --- Campfire Grill (m21) ---
  {
    id: "OFF-088",
    offerName: "BBQ Sampler Platter $18.99",
    merchantName: "Campfire Grill",
    merchantId: "m21",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 1456,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-089",
    offerName: "25% Off Catering Orders",
    merchantName: "Campfire Grill",
    merchantId: "m21",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 234,
    endDate: "2026-08-15",
  },
  {
    id: "OFF-090",
    offerName: "BOGO Ribs Wednesday",
    merchantName: "Campfire Grill",
    merchantId: "m21",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 1890,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-091",
    offerName: "Campfire Grill Cashback 8%",
    merchantName: "Campfire Grill",
    merchantId: "m21",
    offerType: "cashback",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-10-15",
  },

  // --- Bella Nail Studio (m22) ---
  {
    id: "OFF-092",
    offerName: "Gel Manicure $24.99",
    merchantName: "Bella Nail Studio",
    merchantId: "m22",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 3456,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-093",
    offerName: "Free Nail Art with Full Set",
    merchantName: "Bella Nail Studio",
    merchantId: "m22",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 1234,
    endDate: "2026-07-15",
  },
  {
    id: "OFF-094",
    offerName: "BOGO Pedicure Special",
    merchantName: "Bella Nail Studio",
    merchantId: "m22",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-095",
    offerName: "Bella Rewards Card",
    merchantName: "Bella Nail Studio",
    merchantId: "m22",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 2345,
    endDate: "2026-12-31",
  },

  // --- QuickFix Auto Repair (m23) ---
  {
    id: "OFF-096",
    offerName: "$30 Off Brake Service",
    merchantName: "QuickFix Auto Repair",
    merchantId: "m23",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 567,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-097",
    offerName: "Free Inspection with Repair",
    merchantName: "QuickFix Auto Repair",
    merchantId: "m23",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-098",
    offerName: "10% Off AC Service",
    merchantName: "QuickFix Auto Repair",
    merchantId: "m23",
    offerType: "percentage_savings",
    offerStatus: "expired",
    redemptions: 345,
    endDate: "2025-10-31",
  },
  {
    id: "OFF-099",
    offerName: "Book Online Clickthrough",
    merchantName: "QuickFix Auto Repair",
    merchantId: "m23",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 1234,
    endDate: "2026-12-31",
  },

  // --- Horizon Travel Agency (m24) ---
  {
    id: "OFF-100",
    offerName: "15% Off Beach Packages",
    merchantName: "Horizon Travel Agency",
    merchantId: "m24",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 234,
    endDate: "2026-08-31",
  },
  {
    id: "OFF-101",
    offerName: "$100 Off Flights Over $500",
    merchantName: "Horizon Travel Agency",
    merchantId: "m24",
    offerType: "dollars_off",
    offerStatus: "published",
    redemptions: 567,
    endDate: "2026-10-15",
  },
  {
    id: "OFF-102",
    offerName: "Free Travel Insurance with Cruise",
    merchantName: "Horizon Travel Agency",
    merchantId: "m24",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 123,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-103",
    offerName: "Horizon Miles Loyalty",
    merchantName: "Horizon Travel Agency",
    merchantId: "m24",
    offerType: "loyalty_points",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-104",
    offerName: "Vacation Deals Clickthrough",
    merchantName: "Horizon Travel Agency",
    merchantId: "m24",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 4567,
    endDate: "2026-12-31",
  },

  // --- Maple Street Books (m25) ---
  {
    id: "OFF-105",
    offerName: "BOGO Paperbacks",
    merchantName: "Maple Street Books",
    merchantId: "m25",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 1567,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-106",
    offerName: "20% Off New Releases",
    merchantName: "Maple Street Books",
    merchantId: "m25",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-08-15",
  },
  {
    id: "OFF-107",
    offerName: "Free Bookmark with Purchase",
    merchantName: "Maple Street Books",
    merchantId: "m25",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 2345,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-108",
    offerName: "Spend $50 Get $10 Store Credit",
    merchantName: "Maple Street Books",
    merchantId: "m25",
    offerType: "spend_and_get",
    offerStatus: "published",
    redemptions: 456,
    endDate: "2026-10-31",
  },
  {
    id: "OFF-109",
    offerName: "Book Club Loyalty Points",
    merchantName: "Maple Street Books",
    merchantId: "m25",
    offerType: "loyalty_points",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-110",
    offerName: "Children's Book Fair Click",
    merchantName: "Maple Street Books",
    merchantId: "m25",
    offerType: "clickthrough",
    offerStatus: "archived",
    redemptions: 3456,
    endDate: "2025-12-15",
  },
];
