import { OfferStatus, OfferType } from "@/types/offers";

export interface OfferListItem {
  id: string;
  offerName: string;
  merchantName: string;
  merchantId: string;
  offerType: OfferType;
  offerStatus: OfferStatus;
  redemptions: number;
  endDate: string; // ISO date string
}

export const STATUS_LABELS: Record<OfferStatus, string> = {
  published: "Published",
  draft: "Inactive",
  expired: "Inactive",
  archived: "Inactive",
};

export const OFFER_TYPE_LABELS: Record<OfferType, string> = {
  bogo: "Buy One Get One",
  percentage_savings: "Percentage Off",
  dollars_off: "Dollars Off",
  cashback: "Cashback",
  free_with_purchase: "Free with Purchase",
  price_point: "Fixed Price",
  clickthrough: "Clickthrough",
  loyalty_points: "Loyalty Points",
  spend_and_get: "Spend & Get",
};

export const MOCK_MERCHANTS = [
  { id: "m1", name: "Pizza Palace" },
  { id: "m2", name: "Coffee Corner" },
  { id: "m3", name: "Burger Barn" },
  { id: "m4", name: "Taco Town" },
  { id: "m5", name: "Sushi Station" },
  { id: "m6", name: "Pasta Place" },
  { id: "m7", name: "Smoothie Stop" },
  { id: "m8", name: "Bakery Bliss" },
];

export const MOCK_OFFERS: OfferListItem[] = [
  {
    id: "OFF-001",
    offerName: "50% Off Large Pizza",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 1243,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-002",
    offerName: "Buy One Get One Latte",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 892,
    endDate: "2026-05-15",
  },
  {
    id: "OFF-003",
    offerName: "$5 Off Double Burger",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "dollars_off",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-07-01",
  },
  {
    id: "OFF-004",
    offerName: "Free Chips with Combo",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 567,
    endDate: "2026-04-30",
  },
  {
    id: "OFF-005",
    offerName: "20% Off Sashimi Platter",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "percentage_savings",
    offerStatus: "expired",
    redemptions: 345,
    endDate: "2025-12-31",
  },
  {
    id: "OFF-006",
    offerName: "Lunch Special $9.99",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 2100,
    endDate: "2026-08-15",
  },
  {
    id: "OFF-007",
    offerName: "5% Cashback on Smoothies",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "cashback",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-09-01",
  },
  {
    id: "OFF-008",
    offerName: "Free Cookie with Purchase",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 1567,
    endDate: "2026-03-31",
  },
  {
    id: "OFF-009",
    offerName: "BOGO Breakfast Burrito",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "bogo",
    offerStatus: "archived",
    redemptions: 432,
    endDate: "2025-11-30",
  },
  {
    id: "OFF-010",
    offerName: "30% Off Party Platter",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 189,
    endDate: "2026-07-15",
  },
  {
    id: "OFF-011",
    offerName: "$10 Off Dinner for Two",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "dollars_off",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-10-01",
  },
  {
    id: "OFF-012",
    offerName: "Shop & Save $25 Reward",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "spend_and_get",
    offerStatus: "published",
    redemptions: 756,
    endDate: "2026-06-15",
  },
  {
    id: "OFF-013",
    offerName: "Online Order Redirect",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "clickthrough",
    offerStatus: "published",
    redemptions: 3200,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-014",
    offerName: "Happy Hour BOGO Rolls",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "bogo",
    offerStatus: "published",
    redemptions: 678,
    endDate: "2026-05-31",
  },
  {
    id: "OFF-015",
    offerName: "Summer Smoothie Special",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "price_point",
    offerStatus: "expired",
    redemptions: 1890,
    endDate: "2025-09-15",
  },
  {
    id: "OFF-016",
    offerName: "Birthday Cake Discount",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "percentage_savings",
    offerStatus: "published",
    redemptions: 234,
    endDate: "2026-11-30",
  },
  {
    id: "OFF-017",
    offerName: "Family Pizza Bundle",
    merchantName: "Pizza Palace",
    merchantId: "m1",
    offerType: "price_point",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-08-01",
  },
  {
    id: "OFF-018",
    offerName: "Espresso Loyalty Points",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "loyalty_points",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-12-31",
  },
  {
    id: "OFF-019",
    offerName: "Taco Tuesday $2 Tacos",
    merchantName: "Taco Town",
    merchantId: "m4",
    offerType: "price_point",
    offerStatus: "published",
    redemptions: 4521,
    endDate: "2026-06-30",
  },
  {
    id: "OFF-020",
    offerName: "Weekend Brunch Cashback",
    merchantName: "Pasta Place",
    merchantId: "m6",
    offerType: "cashback",
    offerStatus: "archived",
    redemptions: 312,
    endDate: "2025-10-31",
  },
  {
    id: "OFF-021",
    offerName: "Protein Boost Add-On",
    merchantName: "Smoothie Stop",
    merchantId: "m7",
    offerType: "free_with_purchase",
    offerStatus: "published",
    redemptions: 890,
    endDate: "2026-04-15",
  },
  {
    id: "OFF-022",
    offerName: "Holiday Cookie Box",
    merchantName: "Bakery Bliss",
    merchantId: "m8",
    offerType: "dollars_off",
    offerStatus: "expired",
    redemptions: 567,
    endDate: "2025-12-25",
  },
  {
    id: "OFF-023",
    offerName: "Sushi Date Night Deal",
    merchantName: "Sushi Station",
    merchantId: "m5",
    offerType: "spend_and_get",
    offerStatus: "published",
    redemptions: 145,
    endDate: "2026-09-30",
  },
  {
    id: "OFF-024",
    offerName: "Slider Sampler Special",
    merchantName: "Burger Barn",
    merchantId: "m3",
    offerType: "price_point",
    offerStatus: "draft",
    redemptions: 0,
    endDate: "2026-07-31",
  },
  {
    id: "OFF-025",
    offerName: "Morning Coffee Clickthrough",
    merchantName: "Coffee Corner",
    merchantId: "m2",
    offerType: "clickthrough",
    offerStatus: "archived",
    redemptions: 2345,
    endDate: "2025-08-31",
  },
];
